import React,{useState} from 'react';
import useLocalExperiment from './useLocalExperiment';
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul'}).format(new Date());
const activities=[{id:'walk',name:'가볍게 걷기',type:'실외',icon:'🚶',equipment:'편한 신발',minutes:15},{id:'mobility',name:'가벼운 스트레칭',type:'실내',icon:'🧘',equipment:'편안한 공간',minutes:10},{id:'cycle',name:'편안한 자전거 타기',type:'실외',icon:'🚲',equipment:'자전거·헬멧',minutes:20},{id:'indoor',name:'실내 걷기',type:'실내',icon:'👟',equipment:'편한 신발',minutes:15}];
export default function ActivityHub({user}){
 const [records,setRecords,storageError]=useLocalExperiment(user,'activity',[]),[tab,setTab]=useState('운동 추천'),[location,setLocation]=useState('전체'),[time,setTime]=useState(20),[notice,setNotice]=useState('');
 const [date,setDate]=useState(today),[formError,setFormError]=useState('');
 const relevant=records.filter(item=>item.date===date);
 function log(kind,value,name){if(!user){setFormError('로그인 후 기록해 주세요.');return;}setFormError('');setRecords(current=>[{id:crypto.randomUUID(),date,kind,value,name},...current]);setNotice(`${name} 기록을 저장했어요.`);}
 function submit(e){e.preventDefault();const data=new FormData(e.currentTarget),kind=data.get('kind'),value=Number(data.get('value'));if(!Number.isFinite(value)||value<=0||(kind==='weight'&&value>500)||(kind==='water'&&value>10000)||(kind==='workout'&&value>1440)){setFormError('기록값을 확인해 주세요.');return;}log(kind,value,kind==='weight'?'체중':kind==='water'?'물 마시기':String(data.get('name')||'운동'));e.currentTarget.reset();}
 const candidates=activities.filter(item=>(location==='전체'||item.type===location)&&item.minutes<=time).slice(0,3);
 return <><p className="eyebrow">A LITTLE MOVEMENT</p><h1>나의 활동과 일상 기록</h1><p className="notice">내부 실험 · 활동 후보와 기록은 이 브라우저에 저장됩니다. 소모 열량을 계산하거나 음식 섭취와 상쇄하지 않습니다.</p><div className="segmented">{['운동 추천','운동·물·체중 기록'].map(label=><button key={label} className={tab===label?'selected':''} onClick={()=>setTab(label)}>{label}</button>)}</div>{storageError&&<p className="error" role="alert">{storageError}</p>}{notice&&<p className="notice" role="status">{notice}</p>}{tab==='운동 추천'?<><section className="panel activity-filters"><label>활동 장소<select value={location} onChange={e=>setLocation(e.target.value)}>{['전체','실내','실외'].map(value=><option key={value}>{value}</option>)}</select></label><label>가능한 시간<select value={time} onChange={e=>setTime(Number(e.target.value))}>{[10,15,20,30].map(value=><option value={value} key={value}>{value}분</option>)}</select></label></section><div className="cards activity-cards">{candidates.map(item=><article key={item.id}><div className="activity-illustration">{item.icon}</div><span className="studio-badge">{item.type} · 활동 아이디어</span><h2>{item.name}</h2><p>{item.minutes}분 · {item.equipment}</p><p className="muted">선택한 장소와 가능한 시간에 맞는 후보예요. 편안한 강도로 시작해 보세요.</p><button className="primary" onClick={()=>log('workout',item.minutes,item.name)}>완료한 활동 기록</button></article>)}</div><p className="muted">시간은 실험용 예시입니다. 전문 운동 처방이나 개인 건강 상태 평가를 제공하지 않습니다.</p></>:<section className="panel"><h2>오늘의 작은 기록</h2><label>기록 날짜<input type="date" required value={date} max={today()} onChange={e=>setDate(e.target.value)}/></label><form className="activity-form" onSubmit={submit}><label>기록 종류<select name="kind"><option value="workout">운동 시간 (분)</option><option value="water">마신 물 (ml)</option><option value="weight">체중 (kg)</option></select></label><label>이름<input name="name" maxLength={80} placeholder="산책, 자전거 등"/></label><label>기록값<input name="value" type="number" min="0.1" step="0.1" required/></label><button className="primary">기록 저장</button></form></section>}{formError&&<p role="alert" className="error">{formError}</p>}<section className="panel"><h2>{date} 기록</h2><div className="activity-summary"><span>운동 <strong>{relevant.filter(r=>r.kind==='workout').reduce((sum,r)=>sum+r.value,0)}분</strong></span><span>물 <strong>{relevant.filter(r=>r.kind==='water').reduce((sum,r)=>sum+r.value,0)}ml</strong></span><span>체중 <strong>{relevant.find(r=>r.kind==='weight')?.value??'—'}kg</strong></span></div>{relevant.map(item=><div className="point-event" key={item.id}><span>{item.name} <strong>{item.value}{item.kind==='workout'?'분':item.kind==='water'?'ml':'kg'}</strong></span><button className="text-button" aria-label={`${item.name} 기록 삭제`} onClick={()=>setRecords(current=>current.filter(r=>r.id!==item.id))}>삭제</button></div>)}{!relevant.length&&<p className="muted">아직 활동 기록이 없습니다.</p>}</section></>;
}
