// 신체 정보 입력 → 서버 계산 결과 확인 → 로그인 회원의 목표 저장 순서를 제공한다.
// 저장된 프로필을 초기값으로 사용하고 입력 변경 시 다시 계산하도록 단계 상태를 초기화한다.
import React, {useState} from 'react';

// 목표 유형별 장식 SVG 아이콘을 반환한다.
function GoalIcon({type}) {return <svg viewBox="0 0 24 24" width="27" height="27" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{type==='weight_loss'?<><rect x="4" y="3" width="16" height="18" rx="3"/><path d="M8 7a4 4 0 0 1 8 0l-4 4zM12 7V5"/></>:type==='maintain'?<><path d="M5 19C3 9 10 4 20 3c1 10-3 17-11 16M5 21 16 9"/></>:<><circle cx="15" cy="4" r="2"/><path d="m7 10 4-3 4 4 5 1M12 8l-3 7-5 5M10 14l5 2 2 5M3 8h3M2 12h3"/></>}</svg>}
const types = [['weight_loss','체중 감량',<GoalIcon type="weight_loss"/>],['maintain','유지',<GoalIcon type="maintain"/>],['muscle_gain','근육 증가',<GoalIcon type="muscle_gain"/>]];
// 신체 정보 입력 → 서버 계산 결과 확인 → 로그인 회원의 목표 저장 순서를 제공한다.
export default function GoalSetup({profile,user,busy,api,onSaved}) {
  // 기존 프로필을 우선 복원하고 없는 필드만 화면 기본 입력값을 사용한다. 기본값을 자동 저장하지 않는다.
  const [values,setValues]=useState({height:profile?.height??165,weight:profile?.weight??58,age:profile?.age??user?.age??30,sex:profile?.sex??'female',activity_level:profile?.activity_level??'sedentary',goal_type:profile?.goal_type??'maintain',target_calories:profile?.target_calories??2000});
  // step 0은 입력/재계산 필요, 1은 계산 확인 후 저장 가능, 2는 저장 완료 상태다.
  const [step,setStep]=useState(0),[result,setResult]=useState(profile),[working,setWorking]=useState(false),[error,setError]=useState('');
  const disabled=busy||working;
  // 입력값을 갱신하고 목표 설정의 계산/저장 확인 단계를 초기화한다.
  function change(key,value){setValues(v=>({...v,[key]:value}));setStep(0);setError('');}
  // 현재 입력으로 서버 계산 결과를 받고 저장 전 확인 단계로 이동한다.
  async function next(e){e.preventDefault();setWorking(true);setError('');try{const data={...values};['height','weight','age','target_calories'].forEach(k=>data[k]=Number(data[k]));const preview=await api('/profiles/calorie-preview',data);setResult(preview);setStep(1);}catch(e){setError(e.message);}finally{setWorking(false);}}
  // 현재 목표 입력을 상위 저장 콜백으로 전달하고 성공 상태를 표시한다.
  async function save(){setWorking(true);setError('');try{await onSaved({...values,height:Number(values.height),weight:Number(values.weight),age:Number(values.age),target_calories:Number(values.target_calories)});setStep(2);}catch(e){setError(e.message);}finally{setWorking(false);}}
  return <div className="goal-layout"><section className="goal-setup"><h1>나의 목표를 설정해요</h1><p className="goal-subtitle">당신에게 맞는 식단을 준비해요.</p>{error&&<p className="error" role="alert">{error}</p>}
<form onSubmit={next}><fieldset disabled={disabled}><legend>목표 유형</legend><div className="goal-types">{types.map(([value,label,icon])=><button type="button" key={value} className={values.goal_type===value?'selected':''} aria-pressed={values.goal_type===value} onClick={()=>change('goal_type',value)}><span aria-hidden="true">{icon}</span>{label}</button>)}</div><h2>기본 정보</h2><div className="goal-basics"><div className="goal-sex"><span>성별</span>{[['male','남성'],['female','여성']].map(([v,label])=><button type="button" key={v} aria-pressed={values.sex===v} className={values.sex===v?'selected':''} onClick={()=>change('sex',v)}>{label}</button>)}</div><label>만 나이<div className="goal-unit"><input type="number" min="18" max="120" step="1" required value={values.age} onChange={e=>change('age',e.target.value)}/><span>세</span></div></label>{[['height','키','cm',300],['weight','체중','kg',500]].map(([key,label,unit,max])=><label key={key}>{label}<div className="goal-unit"><input type="number" min="0.1" max={max} step="0.1" required value={values[key]} onChange={e=>change(key,e.target.value)}/><span>{unit}</span></div></label>)}</div><label className="goal-activity">활동 수준<select value={values.activity_level} onChange={e=>change('activity_level',e.target.value)}>{[['sedentary','좌식 생활'],['light','가벼운 활동'],['moderate','보통 활동'],['active','활발한 활동']].map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><h2>1일 목표 칼로리</h2><div className="goal-calories"><button type="button" aria-label="목표 칼로리 50 줄이기" onClick={()=>change('target_calories',Math.max(1,Number(values.target_calories)-50))}>−</button><label><span className="sr-only">1일 목표 칼로리</span><input type="number" min="1" max="5000" step="any" required value={values.target_calories} onChange={e=>change('target_calories',e.target.value)}/><span>kcal</span></label><button type="button" aria-label="목표 칼로리 50 늘리기" onClick={()=>change('target_calories',Math.min(5000,Number(values.target_calories)+50))}>+</button></div><h2>탄단지 목표 비율</h2><div className="goal-macros">{['탄수화물','단백질','지방'].map(name=><div key={name}>{name}<strong>미설정</strong></div>)}</div><p className="goal-note">목표 비율은 기준 확정 후 설정할 수 있어요.</p><button className="primary goal-next" disabled={disabled}>{working?'계산 중…':'목표 칼로리 계산하기 →'}</button></fieldset></form>
</section><section className="goal-setup goal-result" aria-live="polite"><h2>목표 칼로리 범위</h2>{result?<div className="goal-review"><strong className="goal-total">{Number(result.target_calories).toLocaleString()} <small>kcal / 일</small></strong><dl>{[['bmr','기초대사량'],['tdee','일일 에너지 소비량'],['minimum_calories','최소 허용값'],['recommended_calorie_min','권장 하한'],['recommended_calorie_max','권장 상한']].map(([key,label])=><div key={key}><dt>{label}</dt><dd>{result[key]} kcal</dd></div>)}</dl>{result.outside_recommended_range&&<p className="notice">입력한 목표가 권장 범위 밖입니다.</p>}<p className="goal-note">{result.notice}</p>{step===1&&user&&<button className="primary goal-next" disabled={disabled} onClick={save}>{working?'저장 중…':'목표 저장하기'}</button>}{step===0&&<p className="goal-note">저장된 값 또는 이전 계산 결과입니다. 입력을 바꿔다면 다시 계산해 주세요.</p>}{step===2&&<p className="notice" role="status">목표가 저장되었습니다.</p>}{!user&&<p className="goal-note">목표 저장은 로그인 후 사용할 수 있습니다.</p>}</div>:<p className="empty">왼쪽에서 정보를 입력하고 목표 칼로리를 계산해 주세요.</p>}</section></div>;
}
