import React,{useEffect,useRef,useState} from 'react';
import PhotoInput from './PhotoInput';
const normalize=text=>text.replace(/\s/g,'').trim();
export default function MenuVision({foods,api,user,onNavigate}){
 const [file,setFile]=useState(null),[text,setText]=useState(''),[busy,setBusy]=useState(false),[percent,setPercent]=useState(0),[error,setError]=useState(''),[result,setResult]=useState(null);
 const worker=useRef(null),generation=useRef(0);
 useEffect(()=>()=>{generation.current++;worker.current?.terminate();},[]);
 const lines=[...new Set(text.split(/\n/).map(line=>line.replace(/[₩￦]?\s*[\d,]+\s*(원|KRW)?\s*$/i,'').trim()).filter(Boolean))];
 const matched=foods.filter(food=>lines.some(line=>normalize(line)===normalize(food.food_name)));
 async function recognize(){if(!file)return;const request=++generation.current;setBusy(true);setError('');setPercent(0);setResult(null);let ownedWorker;try{const {createWorker}=await import('tesseract.js');const w=await createWorker('kor+eng',1,{logger:message=>{if(request===generation.current&&message.status==='recognizing text')setPercent(Math.round(message.progress*100));}});if(request!==generation.current){await w.terminate();return;}ownedWorker=w;worker.current=w;const response=await w.recognize(file);if(request===generation.current)setText(response.data.text);}catch{if(request===generation.current)setError('글자를 읽지 못했습니다. 네트워크 연결을 확인하거나 메뉴명을 직접 입력해 주세요.');}finally{await ownedWorker?.terminate();if(worker.current===ownedWorker)worker.current=null;if(request===generation.current)setBusy(false);}}
 function cancel(){generation.current++;worker.current?.terminate();worker.current=null;setBusy(false);setError('분석을 취소했습니다.');}
 async function recommend(){if(!user){onNavigate('로그인');return;}setBusy(true);setError('');try{const data=await api('/recommendations/meals',{meal_type:'dinner',exclude_foods:foods.filter(food=>!matched.some(item=>item.class_id===food.class_id)).map(food=>food.class_id)});setResult(data);}catch(err){setError(err.message);}finally{setBusy(false);}}
 return <><p className="eyebrow">MENU VISION</p><h1>메뉴판에서 다음 한 끼 찾기</h1><p className="muted">사진의 글자를 확인하고, 영양 데이터가 있는 메뉴만 비교해요.</p><div className="two-col"><section className="panel"><h2>01 · 메뉴판 사진</h2><PhotoInput file={file} busy={busy} onChange={next=>{setFile(next);setResult(null);setError('');}}/><button className="primary" disabled={busy||!file} onClick={recognize}>{busy?`분석 중 ${percent}%`:'메뉴판 글자 읽기'}</button>{busy&&<button className="text-button" onClick={cancel}>취소</button>}<p className="muted">OCR은 브라우저에서 처리됩니다. 첫 실행 시 인식 엔진과 한국어·영어 자료 다운로드에 인터넷 연결이 필요합니다.</p></section><section className="panel"><h2>02 · 메뉴명 확인·수정</h2><label>한 줄에 메뉴 한 개<textarea rows={10} value={text} onChange={e=>{setText(e.target.value);setResult(null);}} placeholder="메뉴 이름을 한 줄씩 입력하세요."/></label><p className="muted">{"\uCD94\uCC9C\uC740 \uC601\uC591 \uB370\uC774\uD130\uC640 \uC77C\uCE58\uD558\uB294 \uBA54\uB274\uAC00 3\uAC1C \uC774\uC0C1\uC77C \uB54C \uAC00\uB2A5\uD574\uC694."}</p><p>{lines.length}개 이름 · 기존 데이터와 일치한 메뉴 {matched.length}개</p><ul>{lines.map(line=><li key={line}>{line} <span className="muted">{foods.some(food=>normalize(food.food_name)===normalize(line))?'· 영양 데이터 있음':'· 연결된 영양 데이터 없음'}</span></li>)}</ul><button className="primary" disabled={busy||matched.length<3} onClick={recommend}>이 메뉴에서 추천받기</button><p className="muted">이름이 일치해도 실제 식당의 조리법·양과 다를 수 있습니다. 기존 음식 기준 영양값으로만 비교합니다.</p></section></div>{error&&<p className="error" role="alert">{error}</p>}{result&&<><p className="notice">{result.notice}</p><div className="cards">{result.items.map(item=><article key={item.class_id}><h2>{item.food_name}</h2><strong>{item.nutrition.cal} kcal</strong><p className="muted">기존 음식 데이터 기준 · {item.unit}</p><ul>{item.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul><button className="outline" onClick={()=>onNavigate('음식 추가')}>음식 확인하고 기록하기</button></article>)}</div></>}</>;
}
