import React,{useEffect,useState} from 'react';
const types={breakfast:'아침',lunch:'점심',dinner:'저녁',snack:'간식'};
export default function RecordCalendar({history,onAdd,api}) {
 const now=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul'}).format(new Date());
 const [month,setMonth]=useState(now.slice(0,7)),[selected,setSelected]=useState(now);
 const [year,m]=month.split('-').map(Number),days=new Date(year,m,0).getDate(),offset=new Date(year,m-1,1).getDay();
 const [loaded,setLoaded]=useState(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;setLoaded(null);setError('');api(`/analytics/month?year=${year}&month=${m}`).then(data=>{if(active)setLoaded(data.days.flatMap(day=>day.meals||[]));}).catch(err=>{if(active)setError(err.message);});return()=>{active=false;};},[api,year,m,history,retry]);
 const entries=loaded||[],records=entries.filter(item=>item.meal_date===selected);
 function move(delta){const d=new Date(year,m-1+delta,1);const next=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;setMonth(next);setSelected(`${next}-01`);}
 return <section className="panel record-calendar"><div className="section-heading"><div><p className="eyebrow">ONE MEAL AT A TIME</p><h2>나의 식단 캘린더</h2></div><div className="calendar-controls"><button onClick={()=>move(-1)} aria-label="이전 달">‹</button><strong>{year}년 {m}월</strong><button onClick={()=>move(1)} aria-label="다음 달">›</button></div></div>{error?<div role="alert"><p className="error">{error}</p><button className="text-button" onClick={()=>setRetry(n=>n+1)}>{"\uB2E4\uC2DC \uBD88\uB7EC\uC624\uAE30"}</button></div>:!loaded?<p role="status">{"\uAE30\uB85D\uC744 \uBD88\uB7EC\uC624\uACE0 \uC788\uC2B5\uB2C8\uB2E4?"}</p>:null}<div className="calendar-days">{['일','월','화','수','목','금','토'].map(d=><span key={d}>{d}</span>)}{Array.from({length:offset},(_,i)=><span key={`empty${i}`}/>)}{Array.from({length:days},(_,i)=>{const date=`${month}-${String(i+1).padStart(2,'0')}`,has=entries.some(item=>item.meal_date===date);return <button key={date} className={selected===date?'selected':''} aria-label={`${date}${has?' · 기록 있음':''}`} aria-pressed={selected===date} onClick={()=>setSelected(date)}>{i+1}<i className={has?'has-record':''}/></button>;})}</div><div className="calendar-selected"><h3>{selected}의 식단</h3>{records.length?<div className="calendar-meals">{records.map(record=><article key={record.id}><span>{types[record.meal_type]}</span><h3>{record.items.map(item=>item.food_name).join(', ')}</h3><strong>{Math.round(record.items.reduce((sum,item)=>sum+(Number(item.nutrition?.cal)||0),0))} kcal</strong></article>)}</div>:<p className="muted">이 날짜에 불러온 기록이 없습니다. 아래 표에서 조회된 기록을 확인하세요.</p>}<button className="text-button" onClick={onAdd}>오늘 식단 추가하기 ＋</button></div><p className="muted">현재 불러온 식단 기록을 표시합니다.</p></section>;
}
