# 기존 P0 식단·탐지·추천·QA 테이블의 Alembic revision.
# 테이블 생성과 제거 순서는 외래키 의존관계를 고려하며 실행은 Alembic 명령으로 관리한다.
"""Backend Core A: P0 meals, detections, consent and QA. Frozen schema."""
from alembic import op
import sqlalchemy as sa

revision = "20261002_02"
down_revision = "20261002_01"
branch_labels = None
depends_on = None

# 이 revision의 테이블·인덱스·제약을 적용한다. 기존 적용 여부는 Alembic revision 이력으로 관리한다.
def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foods',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('canonical_name', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('model_class', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('serving_unit', sa.String(length=120), nullable=False),
    sa.Column('nutrition_source', sa.String(length=255), nullable=False),
    sa.Column('nutrition', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name'),
    sa.UniqueConstraint('model_class')
    )
    op.create_table('detection_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('image_group_id', sa.String(length=36), nullable=False),
    sa.Column('predicted_label', sa.String(length=120), nullable=False),
    sa.Column('corrected_label', sa.String(length=120), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_logs_image_group_id'), 'detection_logs', ['image_group_id'], unique=False)
    op.create_index(op.f('ix_detection_logs_user_id'), 'detection_logs', ['user_id'], unique=False)
    op.create_table('image_uploads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_uploads_user_id'), 'image_uploads', ['user_id'], unique=False)
    op.create_table('meals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meal_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meals_meal_date'), 'meals', ['meal_date'], unique=False)
    op.create_index(op.f('ix_meals_user_id'), 'meals', ['user_id'], unique=False)
    op.create_table('recommendation_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('nutrition_snapshot', sa.JSON(), nullable=False),
    sa.Column('recommendation_json', sa.JSON(), nullable=False),
    sa.Column('selected_item', sa.Integer(), nullable=True),
    sa.Column('acted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_logs_user_id'), 'recommendation_logs', ['user_id'], unique=False)
    op.create_table('meal_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meal_id', sa.String(length=36), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('detection_log_id', sa.String(length=36), nullable=True),
    sa.Column('predicted_label', sa.String(length=120), nullable=True),
    sa.Column('corrected_label', sa.String(length=120), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('serving_multiplier', sa.Float(), nullable=False),
    sa.Column('nutrition', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('serving_multiplier > 0'),
    sa.ForeignKeyConstraint(['detection_log_id'], ['detection_logs.id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('detection_log_id')
    )
    op.create_index(op.f('ix_meal_items_meal_id'), 'meal_items', ['meal_id'], unique=False)
    op.create_table('retraining_samples',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('detection_log_id', sa.String(length=36), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('predicted_label', sa.String(length=120), nullable=False),
    sa.Column('corrected_label', sa.String(length=120), nullable=False),
    sa.Column('qa_status', sa.String(length=16), nullable=False),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("qa_status IN ('PENDING','APPROVED','REJECTED')"),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['detection_log_id'], ['detection_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retraining_samples_detection_log_id'), 'retraining_samples', ['detection_log_id'], unique=False)
    op.add_column('user_profiles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('oauth_provider', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('oauth_subject', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('model_improvement_consent', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('users', sa.Column('model_improvement_consent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_unique_constraint('uq_users_oauth', 'users', ['oauth_provider', 'oauth_subject'])
    # ### end Alembic commands ###

# 이 revision의 스키마 변경을 역순으로 되돌린다. 실제 실행 시 해당 테이블의 데이터가 제거될 수 있다.
def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('uq_users_oauth', 'users', type_='unique')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'model_improvement_consent_at')
    op.drop_column('users', 'model_improvement_consent')
    op.drop_column('users', 'oauth_subject')
    op.drop_column('users', 'oauth_provider')
    op.drop_column('users', 'age')
    op.drop_column('user_profiles', 'updated_at')
    op.drop_index(op.f('ix_retraining_samples_detection_log_id'), table_name='retraining_samples')
    op.drop_table('retraining_samples')
    op.drop_index(op.f('ix_meal_items_meal_id'), table_name='meal_items')
    op.drop_table('meal_items')
    op.drop_index(op.f('ix_recommendation_logs_user_id'), table_name='recommendation_logs')
    op.drop_table('recommendation_logs')
    op.drop_index(op.f('ix_meals_user_id'), table_name='meals')
    op.drop_index(op.f('ix_meals_meal_date'), table_name='meals')
    op.drop_table('meals')
    op.drop_index(op.f('ix_image_uploads_user_id'), table_name='image_uploads')
    op.drop_table('image_uploads')
    op.drop_index(op.f('ix_detection_logs_user_id'), table_name='detection_logs')
    op.drop_index(op.f('ix_detection_logs_image_group_id'), table_name='detection_logs')
    op.drop_table('detection_logs')
    op.drop_table('foods')
    # ### end Alembic commands ###
